"""Foundation records and action history"""

import sqlalchemy as sa
from alembic import op

from app.db import UTCDateTime

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_items",
        sa.Column("source_reference", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("applicability", sa.JSON(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "simulation_instances",
        sa.Column("scenario_key", sa.String(length=80), nullable=False),
        sa.Column("fixture_version", sa.String(length=40), nullable=False),
        sa.Column("evaluation_at", UTCDateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "loans",
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("loan_identifier", sa.String(length=64), nullable=False),
        sa.Column("client_code", sa.String(length=60), nullable=False),
        sa.Column("borrower_display_name", sa.String(length=120), nullable=False),
        sa.Column("balance_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("balance_minor >= 0", name="positive_balance"),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "simulation_id"),
        sa.UniqueConstraint("simulation_id", "loan_identifier"),
    )
    op.create_index(op.f("ix_loans_simulation_id"), "loans", ["simulation_id"], unique=False)
    op.create_table(
        "cases",
        sa.Column("loan_id", sa.String(length=36), nullable=False),
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("creation_key", sa.String(length=36), nullable=False),
        sa.Column("creation_hash", sa.String(length=64), nullable=False),
        sa.Column("ccid", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("correspondence_text", sa.Text(), nullable=False),
        sa.Column("family", sa.String(length=40), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("original_received_at", UTCDateTime(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.Column("classification", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("revision >= 1", name="positive_case_revision"),
        sa.ForeignKeyConstraint(
            ["loan_id", "simulation_id"],
            ["loans.id", "loans.simulation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("creation_key"),
        sa.UniqueConstraint("simulation_id", "ccid"),
    )
    op.create_index(op.f("ix_cases_loan_id"), "cases", ["loan_id"], unique=False)
    op.create_index(
        op.f("ix_cases_original_received_at"), "cases", ["original_received_at"], unique=False
    )
    op.create_index(op.f("ix_cases_simulation_id"), "cases", ["simulation_id"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("case_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("model_configuration", sa.JSON(), nullable=False),
        sa.Column("lease_owner", sa.String(length=120), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("lease_expires_at", UTCDateTime(), nullable=True),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_runs_case_id"), "agent_runs", ["case_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_table(
        "concerns",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("disposition", sa.String(length=40), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_concerns_case_id"), "concerns", ["case_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_reference", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_at", UTCDateTime(), nullable=True),
        sa.Column("storage_key", sa.String(length=200), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_case_id"), "evidence", ["case_id"], unique=False)
    op.create_table(
        "response_drafts",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("case_revision", sa.Integer(), nullable=False),
        sa.Column("response_type", sa.String(length=40), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("evidence_versions", sa.JSON(), nullable=False),
        sa.Column("attachment_ids", sa.JSON(), nullable=False),
        sa.Column("disclosure_ids", sa.JSON(), nullable=False),
        sa.Column("validation", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "version"),
    )
    op.create_index(
        op.f("ix_response_drafts_case_id"), "response_drafts", ["case_id"], unique=False
    )
    op.create_table(
        "specialist_tasks",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("task_type", sa.String(length=80), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("pending_reason", sa.Text(), nullable=True),
        sa.Column("next_review_at", UTCDateTime(), nullable=True),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_specialist_tasks_case_id"), "specialist_tasks", ["case_id"], unique=False
    )
    op.create_table(
        "action_receipts",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "idempotency_key"),
    )
    op.create_index(
        op.f("ix_action_receipts_case_id"), "action_receipts", ["case_id"], unique=False
    )
    op.create_table(
        "review_decisions",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("draft_version", sa.Integer(), nullable=False),
        sa.Column("case_revision", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["response_drafts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_decisions_case_id"), "review_decisions", ["case_id"], unique=False
    )
    op.create_table(
        "case_events",
        sa.Column("sequence", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("action_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["action_receipts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("sequence"),
        sqlite_autoincrement=True,
    )
    op.create_index(op.f("ix_case_events_case_id"), "case_events", ["case_id"], unique=False)
    op.create_table(
        "final_notes",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("action_id", sa.String(length=36), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("note_type", sa.String(length=80), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["action_receipts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id"),
    )
    op.create_index(op.f("ix_final_notes_case_id"), "final_notes", ["case_id"], unique=False)
    op.create_table(
        "indexed_packages",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("action_id", sa.String(length=36), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("index_fields", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["action_receipts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id"),
    )
    op.create_index(
        op.f("ix_indexed_packages_case_id"), "indexed_packages", ["case_id"], unique=False
    )
    op.create_table(
        "outbox_entries",
        sa.Column("action_id", sa.String(length=36), nullable=False),
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("delivery_reference", sa.String(length=120), nullable=False),
        sa.Column("sent_content", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["action_receipts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["response_drafts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id"),
        sa.UniqueConstraint("delivery_reference"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox_entries")
    op.drop_index(op.f("ix_indexed_packages_case_id"), table_name="indexed_packages")
    op.drop_table("indexed_packages")
    op.drop_index(op.f("ix_final_notes_case_id"), table_name="final_notes")
    op.drop_table("final_notes")
    op.drop_index(op.f("ix_case_events_case_id"), table_name="case_events")
    op.drop_table("case_events")
    op.drop_index(op.f("ix_review_decisions_case_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index(op.f("ix_action_receipts_case_id"), table_name="action_receipts")
    op.drop_table("action_receipts")
    op.drop_index(op.f("ix_specialist_tasks_case_id"), table_name="specialist_tasks")
    op.drop_table("specialist_tasks")
    op.drop_index(op.f("ix_response_drafts_case_id"), table_name="response_drafts")
    op.drop_table("response_drafts")
    op.drop_index(op.f("ix_evidence_case_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_concerns_case_id"), table_name="concerns")
    op.drop_table("concerns")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_case_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_cases_simulation_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_original_received_at"), table_name="cases")
    op.drop_index(op.f("ix_cases_loan_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_loans_simulation_id"), table_name="loans")
    op.drop_table("loans")
    op.drop_table("simulation_instances")
    op.drop_table("knowledge_items")
    # ### end Alembic commands ###
